## Turning individual notes into vectors to be placed into the database
import array
import json
import os
import numpy as np
from sentence_transformers import SentenceTransformer
from sqlalchemy import JSON # type: ignore

# Load a pre-trained model
model = SentenceTransformer('all-mpnet-base-v2')

texts = [
"What would you do if you weren't afraid?",
"What does winning look like and mean to you?",
"Don't take life to seriously #life",
"Should be creating cool shit ",
"It's your life, no one cares about your struggle or how hard you've had it in life compared to others", 
"The purpose of life is to simply live,",
"Learn from your own struggle and story along with the struggles and stories of those you look up to / others.#life",   
"We shouldn't go to war unless we have to, people will argue but it's the truth. #political",
"We are not number 1 @ everything, thinking so is fucking retarded (Patriotism vs Nationalism). #political", 
"Small businesses and American made products will always be the backbone of our nation. #political #business", 
"You do not owe anybody anything",
"You do not have to entertain people. #life #truth",
"You have to go back to the basics every once and awhile. #life #progression #software #keepinmind",
"The key to success is to focus on yourself. #life #progression #truth #keepinmind",
"Work smarter and harder then them. #life #motivation #howyouwork",
"You don't thrive or progress in your comfort zone.", 
"Humans are already adapt to work from a place of stability and comfort.", 
"If you're taking yourself out of your comfort zone it should be for a reason and to improve. #life #keepinmind #truth #software #workingout",
"Restart , reset, refocus as many times as you need. #life #mentalhealth #keepinmind #progression",
"No one cares about your feelings. #life #truth #motivation #progression",
"No one is coming for you.",
"There is no 2nd coming of Jesus.", 
"We are with almost complete certainty living within a simulation as everything in science and underlying universal laws and processes suggest. Not an argument. #life #truth #software #keepinmind #religion",
"If you're failing you are the cause, do not blame others. #life #truth #philosophy #progression",  
"The world is languishing to the degree that you are not all you could be. #life #truth #motivation #favorite #keepinmind #progression",   
"Work from a logical standpoint and make appropriate decisions that facilitate progress towards your goals.",
"Do not feel the need to explain yourself and don't concern yourself with the opinions and criticisms of people that have no expertise within the domain that you are working in.",
"Let go of lust and chasing women, not really concerned with being in a relationship till I'm in my 30s. There is nothing wrong with having friends.",
"Allow people to come into your life and leave as they see fit but have boundaries and allow yourself to cut off people that shit on you and your progress.", 
"You deserve the life that you work for.",
"You do not have to be liked and wanting to be is a weakness. #life #truth #motivation #progression #mentalhealth #keepinmind",  
"Train yourself to let stupid people win arguments",
"If your in a situation where people are being dumb as hell simply stop caring what people think.", 
"You quite literally have all the knowledge that you need to be successful but you should still be adaptable. #life #keepinmind #progression",
"You are not perfect, you make mistakes and you do not always have everything together.",
"You have to trust in the processes that you have set in place for yourself along with the logical processes that have been set in place for you to facilitate growth and progression and keep putting the work in. #life #truth #motivation #keepinmind #progression",  
"Keep moving forward and progressing. #life #motivation #progression #keepinmind",
"Lithium Refining is expected to keep growing and be a profitable business. #business #money #investing #future #science", 
"Thoughts on collective consciousness going into the future.  #science #future #tech #software #writting #videogames",
"Thoughts on inhabitable planets and how they became that way #science #space #analysis #research",
"The study of the development, acquisition and use or purpose of resources. #science #business #space #tech #research", 
"Book to read Brave New World #book", 
"Sometimes all you need is a simple change in mindset to accomplish a hard task or make a seemingly hard task easy to accomplish. #life #software #keepinmind #progression", 
"As you keep optimizing their is less to optimize and you add the ability to put together systems.", 
"Through iterative processes you end up creating the best version of the system that you are working on.", 
"You need to make sure your selecting the correct tool for the job in every aspect of software. #software #optimization #performance #progression #keepinmind",
"Thoughts on combining AI and Quantum software or technologies and how they work with and against one another. #ai #quantum #software #tech #research", 
"Dyson sphere (harnessing energy) and self replicating robots, robots that build themselves at a level that is just before fully autonomous. #science #robotics #future #tech #research", 
"Work on yourself more then you do at your job. #life #philosophy #keepinmind #progression", 
"Staying in the fight, continue putting the work in even when you've been overworking yourself, you likely give no fucks about anyone's advice and are going through the motions at this point. #life  #keepinmind #progression #motivation", 
"If you're not putting in the work you are falling behind. #life #motivation #philosophy #keepinmind #progression", 
"Your ability to educate yourself, while your employed vs when your are unemployed. #life #software #writting",
"Money is simply a tool that allows you to progress, how you spend it determines how you progress. #life #philosophy #money #keepinmind",
"The ability to step back, analyze a situation or problem and be wrong at times is a skill and you should be able to adapt from it. #life #progression #keepinmind", 
"Progression in education is almost always linear in reference to time and effort within a subjective domain. #life #education #keepinmind #progression",  
"Getting drunk even for one night is going to set you back a few days in terms of progress in bodybuilding. #life #truth #philosophy #keepinmind #progression #workingout",  
"Your finances are your own responsibility. #life #truth #philosophy #money #business", 
"You can handle whatever life throws at you and you should only accept the appropriate outside pressure. #life #truth #motivation #progression #keepinmind", 
"You don't have diabetes #life #truth",
"Being in good shape and working out is going to be beneficial to your mental health. #mentalhealth #life #keepinmind #truth #motivation",
"Do not allow old people to distract you or get in the way of your goals. #life #progression #keepinmind",
"You shouldn't take your family so seriously but don't allow them to interfere with your career or your life. #life #family #keepinmind #mentalhealth", 
"You shouldn't be stressed. #life #mentalhealth #keepinmind #progression",
"The Goal isn't to make life as easy as possible. #life #keepinmind #mentalhealth",  
"Practice Stoicism and uphold the moral obligations that you have for yourself. #life #philosophy #progression",   
"Know your worth, add value to every room you step foot in but don't let jokes disguised as disrespect allow you to put limits on your value if people are attempting to do so then put them in their place (so you can do what I'm doing better then how I'm doing it? they likely can't and if they can approach things from a learning perspective) or your ability to add it. Keep it stupid simple (KISS). If you don't need my help, THEN YOU DONT NEED MY HELP, leave me alone. #life #keepinmind #business #relationships", 
"Don't be a bitch. #life", 
"Journaling while improving yourself is necessary, otherwise your embracing blind chaos, it allows you to have structure and organization to your thoughts. #life #keepinmind #mentalhealth #progression", 
"You do not owe anybody shit, there are no handouts, provide value to those who provide value to you.", 
"The first Americans had nothing when they expanded into the West. #life #political #philosophy #keepinmind #business #money", 
"I hate weakness. #life #truth #keepinmind #philosophy",
"I'm not going to quit dipping. #life #truth #mentalhealth",
"There is a lot of history in reference to software that you don't know. #note #truth #keepinmind #self-improvement",
"People shouldn't be sticking their heads into your business and acting like their opinion really matters. #life #business #truth",
"You cannot go back in time further then time itself (big-bang). #science #space",
"A username is just 2 words that don't belong together put together, usually with some numbers. #software #note #life #general",
"A lot of Western books involve traveling on a caravan with supplies. #book",
"Writing software to interact with virtual hardware. #software #tech #research #robotics",
"Elon Musk has engineers working 80-100 hours a week.  #life #howyouwork  #motivation #progression #mentalhealth #business #money",  
"Tired isn't an excuse and it's also a mindset that can be easily overcome.",
"Gather free assets whenever you can. #life #advice #software",
"Number of galaxies in the universe 100-200 billion. #science #note",
"You can run windows 11 on an iphone. #science #note #keepinmind",
"Prince of Persia Rival Swords is one of your favorite old school videogames. #videogames #stufftobuy",
"1/2 acre of land cost $50,000-$100,000. #business #money #keepinmind",
"Nvidia Blackwell Platform. #software #note",
"Florida College Football. #life #health",
"Rural king has good deep cycle batteries. #life #stufftobuy",
"New cool license plate. #life #stufftobuy",
"Use Schwab for your stock investments. #money #business #stufftobuy",
"The ability to observe without evaluating is a high level of intelligence. #life #science #note #truth #intelligence",
"If you want me to do something it should be an invitation.", 
"I don't owe anybody anything.",
"Nobody owes me anything. #life #truth",
"You should design your Github readme from a mobile first perspective", 
"Github folders should be organized towards your target audience. #software #note",
"You can make handmade pixel art using dithering. #cool #design #art",
"A 2024 Thor SUV camper is $106,000 - @ $800/month #life #software #stufftobuy",
"You should always consult your budget and make purchases based on what is going to allow you to be more productive at the current time, in line with your goals and use coupons or saving strategies. #life #stufftobuy #keepinmind #note #advice", 
"Raft survival game. #software #cool #design",
"Pre.dev is a opensource software for building development plans and can give you relative pricing. #software #note",
"Some software skills that you have: Organizational skills, project planning, project management, project oversight, adaptation. #software #note #skills",
"Alan Turing - The Enigma Book #book #software",
"Algorithms: Panos Louridas book #book #software",
"If your Grandparents or others get disrespectful towards you, just walk away. #life #health",
"Lead by example / Here's how you do it. #life #leadership #keepinmind",
"Cobol vs Prolog #software #note #languages",
"You have to get to the money. #money #motivation",
"Great way to start a storyline is to write a sentence and then build off of it. #note #idea #videogames #design",
"There is not a bitch that you need, women often play victim to use and manipulate people into getting what they want. Put a bitch in their place when you need to. They are often money hungry and don't really give a fuck about you.. #life #dating", 		
"You can teach your own lessons and give students a platform to work with. #education #ideas",
"(Stock Market) Investing in computational processors for the next few years is a good idea. #money #ideas #investing",
"The history of the construction of ChatGPT. #software #note #ideas",
"Humans as a bacteria, launching into space and spreading, cool ending, not what it seemed, man enters the game @ some point. Humans are actual aliens. #videogames #ideas #design",
"Focus on yourself, if a tech recruiter reaches out to you, then they reach out to you. #software #keepinmind #money #business",
"You should be networking with professionals with 20+ years of experience. #software #business #keepinmind",
"You can help people form their own company, Its not that complicated. #business #software #money #future",
"Anarchist / Dystopian themed development #cool #design",
"Its the 21st century your perception of the world is the technological lens in which you view it from #software #tech #keepinmind #design", 
"You got a 97 because that's all you could get I got a 100 because that's all there was to get. #life #motivation",
"Augmented Reality to increase item significance #software #design",
"When people start bitching to you, do you diet/ do you workout, baseline of being human. #life #health #keepinmind",
"You can go a long time without hitting a plateau while stacking on muscle, You're body will eventually hit a transformative stage where it now understands how to use the newly formed muscle and what its capable of. #life #health #bodybuilding #truth",
"Chatbot FAQ reduces stress #software #design #note",
"Practice Emotional Intelligence #life #advice #keepinmind", 
"The simple biology of cannabis (paranoid / pressure) #note #science", 
"The parents are almost always at fault for the kids shitty behavior. #life #keepinmind",
"God complex cant be killed character for a videogame (main character, side character, enemy) #videogame #design #ideas", 
"Creating videogames will give you a break from work. #note #work #keepinmind #videogames #software #health",
"They are trying to keep you broke.",
"Main character in a videogame using a useful bot to help them out in the game. #videogames #design", 
"We are all hooked to machines and the government is doing experiments on us involving the use of cannabis (long story line with an ending “this is what was going on the entire time”) #videogames #ideas #future",  
"Next generation of technology will be built around reducing number of applications and creating useful meaningful interfaces while utilizing AI and ML. Software is going to be forced to revolutionize at some point since we keep revolutionizing infrastructure, it's only a matter of time. #software #artificial-intelligence #future", 
"Star-history.com for open source software #software #optimization #ideas",
"There is time for large conceptual thinking and there is time for placing the pieces together & there is time for optimization #software #design #optimization #ideas", 
"ChatGPT can supplement complex code well but can't write out entire ML scripts #software #ideas #artificial-intelligence #keepinmind",
"API's used to access large datasets #oftware #ideas #keepinmind",
"Access and Authentication #software #ideas",
"Intersect Observer API #software #ideas",
"Open-mindedness in reference to coming up with new ideas and approaches within software development. #software #ideas #keepinmind #education",
"Feynman lectures on physics #education #physics #books",
"Logic gates and circuits #software #keepinmind",
"Let them win arguments and go be faggots #life #advice", 
"Winget terminal command for updating all applications #software #note", 
"I don't foster an environment that it is cool to be broke, you should always be goal oriented, and improving yourself as a man. #money #business #self-improvement #philosophy",
"If your not putting in the work you're falling behind- For Uber Driving (7am-10am)(5pm-9pm), Estimated $6 an hour after expenses, Uber for around 30 hours per week gets you approx. $200 per week. #money #life #business",                         
"Keep standard of living relatively low #life #money",
"Recurring Costs for(software, bodybuilding, life ($80 at Aldi for 2 weeks of groceries), Other) #life #money #keepinmind", 
"Be looking to install a new motor into your SUV #life #money #keepinmind", 
"Goal no debt and good credit #money #business #keepinmind",
"Conda environment should be customized with the packages you need to get your work done. #software #keepinmind #artificial-intelligence", 
"Microsoft exams cost around $150-$200 #software #keepinmind #money",
"Web design in 1hr and 30min processes, creating a website takes a day #software #design #money",
"More UI's for your toolkit, HTML templates and elements #software #design",
"AI bot for simulating customers #software #design #ideas",
"Do not feel pressured into taking any job offer, your skills are worth at least $100k #software #money #business",
"System Design Principles #software #design #note",
"List of all the different types of games you can create (ex. 4 players on a quest) #videogames #software #ideas",
"Devops and general tech certs #software #education",
"Ways to automate with python #software #artificial-intelligence",
"If I were to hand you a book at 21, 30 and 40 to be successful what would be in it. #self-improvement #ideas",
"Control your shadow in a videogame #videogame #software #design #ideas",
"Allowing yourself to work in environments full of distractions @ times (pros and cons)(leveraging chaos) #work #self-improvement #ideas", 
"All the shit surrounding your dad is mentally limiting, let it go.  #life #advice #self-improvement",
"You should have complete understanding of your surroundings. #life #self-improvement #advice",
"I don't really care what you think. #life #self-improvement",
"Your curiosity shouldn't just be is there a good time going on, you need to advance in your education. #life #education #self-improvement", 
"You can toughen up your Chromebook and personalize it's appearance. #software #stufftobuy",
"People truly don't really give a fuck, they are typically focused on themselves in their own little world. #life #truth #self-improvement",
"Don't put limits on yourself.",
"Don't allow others to put limits on you. #life #advice #motivation",
"Don't allow people to pervert your thoughts. #life #advice",
"You are at an age where it would be a good time to start writing novels. #note #ideas #self-improvement",
"People should be minding their own damn business. #life #truth",
"Don't allow women to manipulate you.",
"You don't need a bitches permission to do shit. #life #dating", 
"Redneck cartoon on a whiskey bottle. #ideas #food/drink",
"You don't have an employee mindset. #note #business #money",
"You're your own boss.",
"Don't allow others to stop you from doing what is beneficial for you. (Should organize this with your other notes on people skills)#keepinmind",    
"Your thoughts should encompass your work and your goals. #work #advice #keepinmind",
"Well if you thought this, I can do this. (Dealing with smart ass kids) #self-improvement",
"Software design from a speech perspective. #software #self-improvement", 
"You don't always have to have everything figured out  or understand everything right away and its fine",
"Study of structures & collisions going through space & bending gravity (tunnel shape), simply altering the state of subatomic particles #science",
"The dust on the moon slowly eats its way through clothing (ferouses material for pest prevention)",
"Effects of everyone having access to mainstream artificial intelligence, everyone has access to it, it's artificial intelligence #software #artificial-intelligence #money",
"What experiments has society already been put through in terms of quantum, revolutionize society and space. Communications is a huge one. #science #space #note",
"Covid could just be conspiracies in quantum and biomechanics Likely is and is likely going to continue to be a thing for the foreseeable future, the government has to enact control somehow",
"No one should be telling you how to think. #life #advice",                         
"Internet Trolls. #software #note",
"Immanuel Kant critique of pure reason, relationship between experience and knowledge, deontological ethics, importance of duty and moral law #philosophy #education", 
"The institutionalization of marijuana. #note #education",
"You should utilize API first design with robust API design principles. #software #note #design",
"Apple offers 1 Million $ to anyone who can hack their virtual AI servers #software #note",
"How AI helps developers instead of replacing them #software #artificial-intelligence #note",
"You should attend a Hacktoberfest #software #note",
"SQL chat easily connects to your database so you can simply ask questions #software #note",
"app.database cool tool to work with databases #software #note",
"You cannot use Docker or virtualization with Shadow Pc #software #note #keepinmind", 
"Fuck people trying to Scam people. #life #money #business",
"Fuck the corrupt bullshit politics #political #note",
"Don't tell me what to do when I'm working #work #note #life",
"Discrimination in AI is a fucking joke and an excuse for people to be alarmist about the subject or a way for them to develop an opinion about what you are working on when they should be minding their own business. #artificial-intelligence #note #keepinmind #political",
"Can respect someone who has created a small business #life #note #business",
"Laws of AI #artificial-intelligence",
"Frontend AI (Generates an user interface for you) #software #artificial-intelligence #note",
"Limits on how many times you can query ChatGPT per day #software #note #keepinmind",
"Rufus software for flashing iso's to USB #software #note #keepinmind",
"Documentation, Planning, Monitoring, Performance, Authentication, Feedback and Iteration #software #note",
"Korbit AI Developer",
"Gacha Tech Stack",
"Node.js frameworks (Hono, Elysia, Nest , Encore.ts)",
"Chatgpt plus 40 prompts per 3 hours  / $20 per month",
"Code GPT for website code creation in VS Code, very basic template to work from",
"Look into AI tools for visual studio 2022",
"Flash BIOS & update OS before backing up to portable SSD",
"Just because AI tools are everywhere doesn't mean people know how to use them for code/progrmaming *customer base*",
"Arch Linux requires a lot of custom setup pacman -Syu for updaets",
"Robotaxis",
"Discrimination in AI is a joke, it's a simple fix",
"Readwise with Obsidian",
"AI in the workplace and how it effects the software manager / ceo -> developer relationship Area here that you need to pay attention of you will develop habits that will ruin a company. Yes the glassdoor reviews on companies do matter & you should take it into consideration.",
"You don't always have it right and that's fine keep working and you'll figure it out later as you make corrections and have time to",
"What is the age of AI version of a data entry clerk",
"Write a book in the future relevant to your notes",
"Jason's a piece of shit",
"High level conceptual analysis, you found that answer, what was the statement that lead you to that answer",
"If a work environment is becoming unproductive to work in, you should be making the adjustments needed to allow it to become productive again.",
"Quit allowing women to get out of hand, at the same time don't be a piece of shit.",
"Don't fall into stupid ass conversations.",
"You typically have a lot of work to do",
"Sometimes you need to write with emotion and sort out all the bullshit.",
"Videogame rewards algorithm",
"Your system is only as good as the tools you use to design it or the code you write for it to work.",
"Underlying Question is always going to be what is the purpose of the simulation / For the fuck of it, to gather some understanding / provides some benefit / or that they are somehow dependent on us. Kinda just is what it is.",
"Kantian Ethics being Optimistic vs Pessimistic (Just be normal and logical)",
"Consciousness and intelligence are proportionate to the knowledge and tools that you have available",
"Creationism",
"The future of working towards eliminating the barriers for creation, simply as a byproduct of professionals needing better tools software and equipment",
"Everything I've seen and studied leans towards a massive war never happening, technology is at a stage where companies are implementing strategies towards the future in retrospect of AI and Quantum with end user adoption still years in the future after that.",
"Design your own drag and drop UI code templator, saves you 2-4 hours everytime that you create a UI.",
"Old people don't get out much and expect you to live life exactly as you have in the past.",
"Don't put limits on yourself because of where your from, you're not dumb.",
"If you need to move on to better your life and progress do so. No one gives a fuck. You should not feel like you have to live in your small hometown.",
"If they're not paying you they can not tell you what to do. The VA is paying you for disabilities that you have for service that you already completed, you have to workout every day and stay healthy.",
"The reels algorithm will preselect reels that it already knows are going to be interesting to you and will keep you guessing what social media is up to all day just so you can see those reels with metrics added in. He's finally scrolling.......Bam....Bam......Bam Hooked on social media.",
"People are going to hate on you for creating content relative to your life but the only other option is consumerism and mediocrity",
"Quantum computer using quantum computation algorithms over the brain responsible for a given task such as motor movement abstracted and turned into a machine learning model", 
"Space viewed through different technological lenses",
"Blockchain over predictive markets",
"Bitcoin blockchain in 500 years in reputation DNA As in your reputation within aspects of technology",
"Using thresholds within engineering and systems",
"Working within your local reality versus 200-500 years out",
"The greatest minds in history all know and agree upon the relative technological landscape that we are working within",
"Faggots keep using emotional AI bullshit to fuck with you",
"A mans strength comes from his work and practices",
"You cant help people who don't want to be helped",
"Quit allowing people to put you in situations where you need help",
"Pay to make an application easier to use",
"If your trailer is sold already it was used to pay your debt to your grandparents, if not then you can give them money at a later date. Not stressed.",
"People are using the I can ask questions shit as an excuse to be annoying and get out of line.",
"Grok AI Chatbot",
"Staying productive in programming is like carrying a hard to carry object for a long distance. After carrying the object long enough you know when to change the position of the object to make it easier to carry. In programming you wake up and know what you need to get done to be more successful.",
"Whiskey into one of the small water dispensers",
"You don't need anyone.",
"You keep trying to argue with me about religion and I don't really give a fuck",
"You can't go any smaller then Quantum",
"The Universe is literally yours",
"Using Virtual reality for mental health.",
"Expected release dates of technology involving supply chains",
"Expect goods and services and how we view things to continue to change at a progressive rate, Dragging along with it our generational technology biased with it",
"They're trying to keep you dumb and broke.",
"People typically criticize in an attempt to make them feel better and they almost always hope that you fail.",
"You'll never find someone outworking you talking shit.",
"Using AI agents as employees.",
"How do we view old infomercials and how do we view current infomercials for AI",
"What algorithms work across fundamental levels and involve life processes",
"You can get a marijuana card if you want.",
"Books on Western developments of society and biographies chill reads",
"Old school gameboy games when text is typed out sounds like a simulation",
"You are currently sorting everything out, add in a bit of structure for art, videogames, websites, 3d modeling, etc. Should come up with an idea for a piece of art that you want to create for the day, spend time developing it and then work on it. There is a time to be disciplined and there is a time to let your mind flow freely. There is a process and structure for professionally and effectively creating art.",
"Allow yourself to think freely in the mornings, journal, coffee, meditations",
"Sometimes people mean smart as in talks a lot of shit, comes from the colossal amount of work that I've had to put in (check your ego) I do talk a lot of shit at times, so does everyone else.",
"They want you to believe that your weakness is Women, its not.",
"Your Moms trying to make you look dumb.",
"Quit overthinking pot, if you smoke you should do so in moderation",
"Cryptography should solidify the fundamentals of Quantum Computing",
"You should be more present in your own life then others",
"If you talk all the time vs if you think all the time",
"I live like a man who has already died, I have no fear of anybody or anything"
]

# Load the SentenceTransformer model (you can change the model to suit your needs)
model = SentenceTransformer('diwank/dfe-base-en-1')

# Output file path (same folder as the script)
output_file_path = os.path.join(os.getcwd(), "obsidian_notes_output.json")

# Prepare a list of dictionaries with id and text
output_data = []

# Iterate through each text and its index
for i, text in enumerate(texts):
    # Create a dictionary with id and text for the current note
    point = {
        "id": i + 1,  # Unique ID for each note (starting from 1)
        "text": text  # The text itself
    }

    # Append the point to the output list
    output_data.append(point)

# Write the output list to the file
with open(output_file_path, 'w') as file:
    json_output = json.dumps(output_data, indent=2)
    file.write(json_output)

print(f"Output written to {output_file_path}")
