# Generated by Django 5.2.3 on 2025-06-25 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_embeddings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_file",
        ),
        migrations.AddField(
            model_name="document",
            name="uploadPDF",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="pdfs/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
